spring:
  datasource:
    url: jdbc:mysql://47.97.90.166:3306/library
    username: root
    password: hn123456Aa.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081